### ISSUE TITLE
Bug: Duplicate Org Questions - Dry Pallets

### ISSUE THREAD

**Issue by Zach-Lenart** [HDSLabs/co-care-exchange-client#106]
URL: https://app.cocareexchange.org/prompt

Under Dry Pallets - Remove Duplicate questions: 
1. Are you requesting or sharing non-perishable items?
2. Are you requesting or sharing baby items?

**Comment by Zach-Lenart** [comment]
![image](https://user-images.githubusercontent.com/63121454/78997174-415db500-7b03-11ea-975a-5d5bee36cb66.png)

**Comment by akilhoffer** [comment]
The duplicate non-perishable question was a copy/paste error and has been fixed. The baby items question didnt seem to have any detail associated with it, so it was just deleted.
