### ISSUE TITLE
Styling: Center Align Numbers in Quantity Text Boxes

### ISSUE THREAD

**Issue by hailerk** [HDSLabs/co-care-exchange-client#116]
See attachment. 

It's nitpicky and dumb, but I just want this to look awesome for our first users. 
<img width="753" alt="Center align" src="https://user-images.githubusercontent.com/13766994/79018483-27d36200-7b31-11ea-926f-fb5b03a3dbfa.png">

**Comment by Zach-Lenart** [comment]
Confirmed the Numbers are now centered in the Quantity Text box

![image](https://user-images.githubusercontent.com/63121454/79072294-83baf980-7c9d-11ea-8628-25959851e55d.png)
