### ISSUE TITLE
When registering new user and password doesnt meet length requirements, show number of characters needed in error dialog.

### ISSUE THREAD

**Issue by akilhoffer** [HDSLabs/co-care-exchange-client#24]
When registering new user and password doesnt meet length requirements, show number of characters needed in error dialog. Right now, it just shows a dialog stating the pw wasnt long enough. But doesn't tell them how long it needs to be.

**Comment by dougpool** [comment]
I made the min password length client validation match the required min password length, so once the valid length is inputted, the form will validate
