### ISSUE TITLE
BUG: Profile screen doesn't pre-populate for existing INDIVIDUAL user

### ISSUE THREAD

**Issue by joshblair** [HDSLabs/co-care-exchange-client#87]

**Comment by Zach-Lenart** [comment]
@joshblair, 

I logged in as an ind. this morning and my address wasn't populating for Johnny Utah. I filled out the address then it sent me to the prompt questions > I requested 1 item then went back to the profile page and my address didn't save.

**Comment by Zach-Lenart** [comment]
@joshblair, 

I tested this again on the URL: https://app.cocareexchange.org/ and everything was brought over besides the family size field. 

Question is this the best URL to do testing on?

Haile gave me this URL :http://ccex-dev.s3-website-us-west-2.amazonaws.com/

**Comment by joshblair** [comment]
@Zach-Lenart, these URLs point to the same site currently. The family size field isn't supported in the back-end yet. Glad to hear the profile is working for you otherwise.
