### ISSUE TITLE
Allow Request and Share Count to be User Entered

### ISSUE THREAD

**Issue by hailerk** [HDSLabs/co-care-exchange-client#98]
- Tommy mentioned that they often request 1,000s of items and clicking the up arrow 1000 times won't work.
- I  like it if we could retain the arrows, so there is the option to type it in or not. (See attached screenshot)

<img width="702" alt="Text Boxes" src="https://user-images.githubusercontent.com/13766994/78846631-9c8b8c80-79c9-11ea-97f8-78fb51c55a66.png">

**Comment by Zach-Lenart** [comment]
Tested on URL: https://app.cocareexchange.org/

Both ORG and IND both had the ability to enter the amount or use the arrows to produce desired amounts. Good to go!
